accumulate_grad_batches: 1
amp_backend: native
amp_level: O2
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: false
b1: 0.0
b2: 0.9
batch_size: 32
benchmark: false
check_val_every_n_epoch: 1
checkpoint_callback: true
data_dir: ./data
default_root_dir: null
deterministic: false
dims:
- 1
- 28
- 28
distributed_backend: null
early_stop_callback: false
fast_dev_run: false
gradient_clip_val: 0
limit_test_batches: 1.0
limit_train_batches: 1.0
limit_val_batches: 1.0
log_gpu_memory: null
log_save_interval: 100
logger: true
lr: 0.0002
max_epochs: 1
max_steps: null
min_epochs: 1
min_steps: null
ngf: 32
normalize: false
num_nodes: 1
num_processes: 1
num_sanity_val_steps: 2
num_workers: 16
overfit_batches: 0.0
overfit_pct: null
precision: 32
prepare_data_per_node: true
process_position: 0
profiler: null
progress_bar_refresh_rate: 1
reload_dataloaders_every_epoch: false
replace_sampler_ddp: true
resume_from_checkpoint: null
row_log_interval: 50
seed: 42
sync_batchnorm: false
terminate_on_nan: false
test_percent_check: null
test_split: 20000
track_grad_norm: -1
train_percent_check: null
truncated_bptt_steps: null
val_check_interval: 1.0
val_percent_check: null
val_split: 10000
weights_save_path: null
weights_summary: top
z_dim: 128
